# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addGoods12.ui'
#
# Created: Fri Jul  6 00:31:22 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_addGoods(object):
    def setupUi(self, addGoods):
        addGoods.setObjectName(_fromUtf8("addGoods"))
        addGoods.resize(640, 315)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(addGoods.sizePolicy().hasHeightForWidth())
        addGoods.setSizePolicy(sizePolicy)
        addGoods.setMinimumSize(QtCore.QSize(640, 315))
        addGoods.setMaximumSize(QtCore.QSize(640, 315))
        self.gridLayout = QtGui.QGridLayout(addGoods)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(addGoods)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Namelabel = QtGui.QLabel(self.tab)
        self.Namelabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Namelabel.setObjectName(_fromUtf8("Namelabel"))
        self.gridLayout_2.addWidget(self.Namelabel, 3, 1, 1, 1)
        self.Countrylabel = QtGui.QLabel(self.tab)
        self.Countrylabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Countrylabel.setObjectName(_fromUtf8("Countrylabel"))
        self.gridLayout_2.addWidget(self.Countrylabel, 6, 1, 1, 1)
        self.CountryEdit = QtGui.QLineEdit(self.tab)
        self.CountryEdit.setObjectName(_fromUtf8("CountryEdit"))
        self.gridLayout_2.addWidget(self.CountryEdit, 6, 2, 1, 4)
        self.Pricelabel = QtGui.QLabel(self.tab)
        self.Pricelabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Pricelabel.setObjectName(_fromUtf8("Pricelabel"))
        self.gridLayout_2.addWidget(self.Pricelabel, 4, 1, 1, 1)
        self.BrendEdit = QtGui.QLineEdit(self.tab)
        self.BrendEdit.setObjectName(_fromUtf8("BrendEdit"))
        self.gridLayout_2.addWidget(self.BrendEdit, 5, 2, 1, 4)
        self.Brandlabel = QtGui.QLabel(self.tab)
        self.Brandlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Brandlabel.setObjectName(_fromUtf8("Brandlabel"))
        self.gridLayout_2.addWidget(self.Brandlabel, 5, 1, 1, 1)
        self.NameEdit = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NameEdit.sizePolicy().hasHeightForWidth())
        self.NameEdit.setSizePolicy(sizePolicy)
        self.NameEdit.setObjectName(_fromUtf8("NameEdit"))
        self.gridLayout_2.addWidget(self.NameEdit, 3, 2, 1, 4)
        self.PriceEdit = QtGui.QLineEdit(self.tab)
        self.PriceEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PriceEdit.sizePolicy().hasHeightForWidth())
        self.PriceEdit.setSizePolicy(sizePolicy)
        self.PriceEdit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.PriceEdit.setObjectName(_fromUtf8("PriceEdit"))
        self.gridLayout_2.addWidget(self.PriceEdit, 4, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 3, 1, 1)
        self.Articlelabel = QtGui.QLabel(self.tab)
        self.Articlelabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Articlelabel.setObjectName(_fromUtf8("Articlelabel"))
        self.gridLayout_2.addWidget(self.Articlelabel, 0, 1, 1, 1)
        self.ArticleEdit = QtGui.QLineEdit(self.tab)
        self.ArticleEdit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ArticleEdit.setText(_fromUtf8(""))
        self.ArticleEdit.setObjectName(_fromUtf8("ArticleEdit"))
        self.gridLayout_2.addWidget(self.ArticleEdit, 0, 2, 1, 2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.NdsEdit = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NdsEdit.sizePolicy().hasHeightForWidth())
        self.NdsEdit.setSizePolicy(sizePolicy)
        self.NdsEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.NdsEdit.setObjectName(_fromUtf8("NdsEdit"))
        self.gridLayout_4.addWidget(self.NdsEdit, 2, 1, 1, 1)
        self.NDSlabel = QtGui.QLabel(self.tab_2)
        self.NDSlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.NDSlabel.setObjectName(_fromUtf8("NDSlabel"))
        self.gridLayout_4.addWidget(self.NDSlabel, 2, 0, 1, 1)
        self.Minnumlabel = QtGui.QLabel(self.tab_2)
        self.Minnumlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Minnumlabel.setObjectName(_fromUtf8("Minnumlabel"))
        self.gridLayout_4.addWidget(self.Minnumlabel, 1, 0, 1, 1)
        self.Measurelabel = QtGui.QLabel(self.tab_2)
        self.Measurelabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Measurelabel.setObjectName(_fromUtf8("Measurelabel"))
        self.gridLayout_4.addWidget(self.Measurelabel, 0, 0, 1, 1)
        self.MeasureEdit = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MeasureEdit.sizePolicy().hasHeightForWidth())
        self.MeasureEdit.setSizePolicy(sizePolicy)
        self.MeasureEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.MeasureEdit.setObjectName(_fromUtf8("MeasureEdit"))
        self.gridLayout_4.addWidget(self.MeasureEdit, 0, 1, 1, 1)
        self.MinimalEdit = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MinimalEdit.sizePolicy().hasHeightForWidth())
        self.MinimalEdit.setSizePolicy(sizePolicy)
        self.MinimalEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.MinimalEdit.setObjectName(_fromUtf8("MinimalEdit"))
        self.gridLayout_4.addWidget(self.MinimalEdit, 1, 1, 1, 12)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.CreateGroupButton = QtGui.QPushButton(self.tab_3)
        self.CreateGroupButton.setObjectName(_fromUtf8("CreateGroupButton"))
        self.gridLayout_3.addWidget(self.CreateGroupButton, 0, 1, 1, 1)
        self.treeWidget = QtGui.QTreeWidget(self.tab_3)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.gridLayout_3.addWidget(self.treeWidget, 0, 0, 5, 1)
        self.EditGroupButton = QtGui.QPushButton(self.tab_3)
        self.EditGroupButton.setObjectName(_fromUtf8("EditGroupButton"))
        self.gridLayout_3.addWidget(self.EditGroupButton, 1, 1, 1, 1)
        self.DeleteGroupButton = QtGui.QPushButton(self.tab_3)
        self.DeleteGroupButton.setObjectName(_fromUtf8("DeleteGroupButton"))
        self.gridLayout_3.addWidget(self.DeleteGroupButton, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 6)
        self.buttonBox = QtGui.QDialogButtonBox(addGoods)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)

        self.retranslateUi(addGoods)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), addGoods.close)
        QtCore.QMetaObject.connectSlotsByName(addGoods)

    def retranslateUi(self, addGoods):
        addGoods.setWindowTitle(QtGui.QApplication.translate("addGoods", "Добавление позиции", None, QtGui.QApplication.UnicodeUTF8))
        self.Namelabel.setText(QtGui.QApplication.translate("addGoods", "Название", None, QtGui.QApplication.UnicodeUTF8))
        self.Countrylabel.setText(QtGui.QApplication.translate("addGoods", "Страна изготовления", None, QtGui.QApplication.UnicodeUTF8))
        self.Pricelabel.setText(QtGui.QApplication.translate("addGoods", "Цена", None, QtGui.QApplication.UnicodeUTF8))
        self.Brandlabel.setText(QtGui.QApplication.translate("addGoods", "Бренд", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceEdit.setText(QtGui.QApplication.translate("addGoods", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("addGoods", "руб", None, QtGui.QApplication.UnicodeUTF8))
        self.Articlelabel.setText(QtGui.QApplication.translate("addGoods", "Артикул", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("addGoods", "Основная информация", None, QtGui.QApplication.UnicodeUTF8))
        #self.NdsEdit.setText(QtGui.QApplication.translate("addGoods", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.NDSlabel.setText(QtGui.QApplication.translate("addGoods", "НДС", None, QtGui.QApplication.UnicodeUTF8))
        self.Minnumlabel.setText(QtGui.QApplication.translate("addGoods", "Минимальное кол-во", None, QtGui.QApplication.UnicodeUTF8))
        self.Measurelabel.setText(QtGui.QApplication.translate("addGoods", "Единица измерения", None, QtGui.QApplication.UnicodeUTF8))
        self.MeasureEdit.setText(QtGui.QApplication.translate("addGoods", "шт.", None, QtGui.QApplication.UnicodeUTF8))
        self.MinimalEdit.setText(QtGui.QApplication.translate("addGoods", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("addGoods", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("addGoods", "Дополнительная информация", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateGroupButton.setText(QtGui.QApplication.translate("addGoods", "Создать", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("addGoods", "Группы", None, QtGui.QApplication.UnicodeUTF8))
        self.EditGroupButton.setText(QtGui.QApplication.translate("addGoods", "Правка", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteGroupButton.setText(QtGui.QApplication.translate("addGoods", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("addGoods", "Группы", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("addGoods", "Штрих коды", None, QtGui.QApplication.UnicodeUTF8))

