# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addPrihod10.ui'
#
# Created: Sun Aug 12 22:46:27 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_addPrihodForm(object):
    def setupUi(self, addPrihodForm):
        addPrihodForm.setObjectName(_fromUtf8("addPrihodForm"))
        addPrihodForm.resize(842, 435)
        self.verticalLayout_2 = QtGui.QVBoxLayout(addPrihodForm)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame = QtGui.QFrame(addPrihodForm)
        self.frame.setStyleSheet(_fromUtf8(""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.prihodLabel = QtGui.QLabel(self.frame)
        self.prihodLabel.setObjectName(_fromUtf8("prihodLabel"))
        self.horizontalLayout.addWidget(self.prihodLabel)
        self.prihodLineEdit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prihodLineEdit.sizePolicy().hasHeightForWidth())
        self.prihodLineEdit.setSizePolicy(sizePolicy)
        self.prihodLineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.prihodLineEdit.setObjectName(_fromUtf8("prihodLineEdit"))
        self.horizontalLayout.addWidget(self.prihodLineEdit)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.prihodDateEdit = QtGui.QDateEdit(self.frame)
        self.prihodDateEdit.setObjectName(_fromUtf8("prihodDateEdit"))
        self.horizontalLayout.addWidget(self.prihodDateEdit)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 2)
        self.contragentLabel = QtGui.QLabel(addPrihodForm)
        self.contragentLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.contragentLabel.setObjectName(_fromUtf8("contragentLabel"))
        self.gridLayout_2.addWidget(self.contragentLabel, 1, 0, 1, 1)
        self.contragentComboBox = QtGui.QComboBox(addPrihodForm)
        self.contragentComboBox.setObjectName(_fromUtf8("contragentComboBox"))
        self.gridLayout_2.addWidget(self.contragentComboBox, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(addPrihodForm)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout = QtGui.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(114, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.line = QtGui.QFrame(self.frame_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 3)
        self.changeButton = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changeButton.sizePolicy().hasHeightForWidth())
        self.changeButton.setSizePolicy(sizePolicy)
        self.changeButton.setObjectName(_fromUtf8("changeButton"))
        self.gridLayout.addWidget(self.changeButton, 5, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 2)
        self.contragentLabel_2 = QtGui.QLabel(self.frame_2)
        self.contragentLabel_2.setObjectName(_fromUtf8("contragentLabel_2"))
        self.gridLayout.addWidget(self.contragentLabel_2, 2, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 2)
        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 2, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.goodsTableWidget = QtGui.QTableWidget(addPrihodForm)
        self.goodsTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.goodsTableWidget.setObjectName(_fromUtf8("goodsTableWidget"))
        self.goodsTableWidget.setColumnCount(6)
        self.goodsTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(5, item)
        self.goodsTableWidget.horizontalHeader().setVisible(True)
        self.goodsTableWidget.horizontalHeader().setHighlightSections(True)
        self.goodsTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.goodsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.goodsTableWidget.verticalHeader().setVisible(True)
        self.horizontalLayout_2.addWidget(self.goodsTableWidget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.goodsButton = QtGui.QPushButton(addPrihodForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goodsButton.sizePolicy().hasHeightForWidth())
        self.goodsButton.setSizePolicy(sizePolicy)
        self.goodsButton.setObjectName(_fromUtf8("goodsButton"))
        self.verticalLayout.addWidget(self.goodsButton)
        spacerItem3 = QtGui.QSpacerItem(20, 278, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.issueButton = QtGui.QPushButton(addPrihodForm)
        self.issueButton.setObjectName(_fromUtf8("issueButton"))
        self.verticalLayout.addWidget(self.issueButton)
        self.cancelButton = QtGui.QPushButton(addPrihodForm)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.verticalLayout.addWidget(self.cancelButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(addPrihodForm)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), addPrihodForm.close)
        QtCore.QMetaObject.connectSlotsByName(addPrihodForm)

    def retranslateUi(self, addPrihodForm):
        addPrihodForm.setWindowTitle(QtGui.QApplication.translate("addPrihodForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.prihodLabel.setText(QtGui.QApplication.translate("addPrihodForm", "Приход №", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("addPrihodForm", "от", None, QtGui.QApplication.UnicodeUTF8))
        self.contragentLabel.setText(QtGui.QApplication.translate("addPrihodForm", "Контрагент", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("addPrihodForm", "Дополнительная информация", None, QtGui.QApplication.UnicodeUTF8))
        self.changeButton.setText(QtGui.QApplication.translate("addPrihodForm", "Изменить", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("addPrihodForm", "Основание документа", None, QtGui.QApplication.UnicodeUTF8))
        self.contragentLabel_2.setText(QtGui.QApplication.translate("addPrihodForm", "Название контрагента", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("addPrihodForm", "Счёт-фактура №", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("addPrihodForm", "Исх. №", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("addPrihodForm", "№ п/п", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("addPrihodForm", "Товар", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("addPrihodForm", "Артикул", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("addPrihodForm", "Цена ", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("addPrihodForm", "Количество", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("addPrihodForm", "Сумма", None, QtGui.QApplication.UnicodeUTF8))
        self.goodsButton.setText(QtGui.QApplication.translate("addPrihodForm", "Товары", None, QtGui.QApplication.UnicodeUTF8))
        self.issueButton.setText(QtGui.QApplication.translate("addPrihodForm", "Оформить", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("addPrihodForm", "Отменить", None, QtGui.QApplication.UnicodeUTF8))

