# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooseGoods3.ui'
#
# Created: Tue Aug 14 20:50:53 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ChooseGoodsForm(object):
    def setupUi(self, ChooseGoodsForm):
        ChooseGoodsForm.setObjectName(_fromUtf8("ChooseGoodsForm"))
        ChooseGoodsForm.resize(845, 499)
        self.verticalLayout = QtGui.QVBoxLayout(ChooseGoodsForm)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(ChooseGoodsForm)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupsTreeWidget = QtGui.QTreeWidget(self.splitter)
        self.groupsTreeWidget.setObjectName(_fromUtf8("groupsTreeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.groupsTreeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.groupsTreeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.groupsTreeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.groupsTreeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.goodsTableWidget = QtGui.QTableWidget(self.splitter)
        self.goodsTableWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.goodsTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.goodsTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.goodsTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.goodsTableWidget.setObjectName(_fromUtf8("goodsTableWidget"))
        self.goodsTableWidget.setColumnCount(11)
        self.goodsTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(10, item)
        self.goodsTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.goodsTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.goodsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.goodsTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.goodsTableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.filter_label = QtGui.QLabel(ChooseGoodsForm)
        self.filter_label.setObjectName(_fromUtf8("filter_label"))
        self.horizontalLayout.addWidget(self.filter_label)
        self.filter_lineEdit = QtGui.QLineEdit(ChooseGoodsForm)
        self.filter_lineEdit.setObjectName(_fromUtf8("filter_lineEdit"))
        self.horizontalLayout.addWidget(self.filter_lineEdit)
        self.clearFilterButton = QtGui.QPushButton(ChooseGoodsForm)
        self.clearFilterButton.setObjectName(_fromUtf8("clearFilterButton"))
        self.horizontalLayout.addWidget(self.clearFilterButton)
        self.okButton = QtGui.QPushButton(ChooseGoodsForm)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.horizontalLayout.addWidget(self.okButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ChooseGoodsForm)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL(_fromUtf8("clicked()")), ChooseGoodsForm.close)
        QtCore.QMetaObject.connectSlotsByName(ChooseGoodsForm)

    def retranslateUi(self, ChooseGoodsForm):
        ChooseGoodsForm.setWindowTitle(QtGui.QApplication.translate("ChooseGoodsForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Группы", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.groupsTreeWidget.isSortingEnabled()
        self.groupsTreeWidget.setSortingEnabled(False)
        self.groupsTreeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Все группы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Водонагреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Проточные водонагреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Накопительные водонагреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Теплотехника", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.topLevelItem(2).child(0).setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Электрические конвекторы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.topLevelItem(2).child(1).setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Маслонаполненные обогреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.topLevelItem(3).setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Водоснабжение", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.topLevelItem(3).child(0).setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Погружные насосы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.topLevelItem(3).child(0).child(0).setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Центробежные погружные насосы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.topLevelItem(3).child(0).child(1).setText(0, QtGui.QApplication.translate("ChooseGoodsForm", "Вибрационные погружные насосы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsTreeWidget.setSortingEnabled(__sortingEnabled)
        item = self.goodsTableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("ChooseGoodsForm", "Артикул", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("ChooseGoodsForm", "Название", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("ChooseGoodsForm", "Ед. изм.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("ChooseGoodsForm", "Цена", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("ChooseGoodsForm", "Свободно", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("ChooseGoodsForm", "В документе", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("ChooseGoodsForm", "В наличии", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("ChooseGoodsForm", "Бренд", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("ChooseGoodsForm", "Страна производства", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("ChooseGoodsForm", "Резерв", None, QtGui.QApplication.UnicodeUTF8))
        item = self.goodsTableWidget.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("ChooseGoodsForm", "В упаковке", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_label.setText(QtGui.QApplication.translate("ChooseGoodsForm", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.clearFilterButton.setText(QtGui.QApplication.translate("ChooseGoodsForm", "Очистить", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setToolTip(QtGui.QApplication.translate("ChooseGoodsForm", "Закрыть окно", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("ChooseGoodsForm", "Ok", None, QtGui.QApplication.UnicodeUTF8))

