# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-test8.ui'
#
# Created: Sat Jul  7 02:07:19 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(997, 693)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.goods_tab = QtGui.QWidget()
        self.goods_tab.setObjectName(_fromUtf8("goods_tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.goods_tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.addGroupButton = QtGui.QPushButton(self.goods_tab)
        self.addGroupButton.setObjectName(_fromUtf8("addGroupButton"))
        self.gridLayout_2.addWidget(self.addGroupButton, 7, 0, 1, 1)
        self.deleteGroupButton = QtGui.QPushButton(self.goods_tab)
        self.deleteGroupButton.setObjectName(_fromUtf8("deleteGroupButton"))
        self.gridLayout_2.addWidget(self.deleteGroupButton, 7, 1, 1, 1)
        self.copyUnitButton = QtGui.QPushButton(self.goods_tab)
        self.copyUnitButton.setObjectName(_fromUtf8("copyUnitButton"))
        self.gridLayout_2.addWidget(self.copyUnitButton, 1, 5, 1, 1)
        self.CloseGoodsButton = QtGui.QPushButton(self.goods_tab)
        self.CloseGoodsButton.setObjectName(_fromUtf8("CloseGoodsButton"))
        self.gridLayout_2.addWidget(self.CloseGoodsButton, 7, 5, 1, 1)
        self.addUnitButton = QtGui.QPushButton(self.goods_tab)
        self.addUnitButton.setObjectName(_fromUtf8("addUnitButton"))
        self.gridLayout_2.addWidget(self.addUnitButton, 0, 5, 1, 1)
        self.editUnitButton = QtGui.QPushButton(self.goods_tab)
        self.editUnitButton.setObjectName(_fromUtf8("editUnitButton"))
        self.gridLayout_2.addWidget(self.editUnitButton, 2, 5, 1, 1)
        self.deleteUnitButton = QtGui.QPushButton(self.goods_tab)
        self.deleteUnitButton.setObjectName(_fromUtf8("deleteUnitButton"))
        self.gridLayout_2.addWidget(self.deleteUnitButton, 3, 5, 1, 1)
        self.treeWidget = QtGui.QTreeWidget(self.goods_tab)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.gridLayout_2.addWidget(self.treeWidget, 0, 0, 7, 2)
        self.filter_label = QtGui.QLabel(self.goods_tab)
        self.filter_label.setObjectName(_fromUtf8("filter_label"))
        self.gridLayout_2.addWidget(self.filter_label, 7, 2, 1, 1)
        self.filter_lineEdit = QtGui.QLineEdit(self.goods_tab)
        self.filter_lineEdit.setObjectName(_fromUtf8("filter_lineEdit"))
        self.gridLayout_2.addWidget(self.filter_lineEdit, 7, 3, 1, 1)
        self.ClearFilterButton = QtGui.QPushButton(self.goods_tab)
        self.ClearFilterButton.setObjectName(_fromUtf8("ClearFilterButton"))
        self.gridLayout_2.addWidget(self.ClearFilterButton, 7, 4, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.goods_tab)
        self.tableWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 2, 7, 3)
        self.tabWidget.addTab(self.goods_tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.CloseGoodsButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tabWidget.close)
        QtCore.QObject.connect(self.ClearFilterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.filter_lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.addGroupButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Добавить группу", None, QtGui.QApplication.UnicodeUTF8))
        self.addGroupButton.setText(QtGui.QApplication.translate("MainWindow", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteGroupButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Удалить группу", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteGroupButton.setText(QtGui.QApplication.translate("MainWindow", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.copyUnitButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Копировать позицию", None, QtGui.QApplication.UnicodeUTF8))
        self.copyUnitButton.setText(QtGui.QApplication.translate("MainWindow", "Копировать", None, QtGui.QApplication.UnicodeUTF8))
        self.CloseGoodsButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Закрыть окно", None, QtGui.QApplication.UnicodeUTF8))
        self.CloseGoodsButton.setText(QtGui.QApplication.translate("MainWindow", "Закрыть", None, QtGui.QApplication.UnicodeUTF8))
        self.addUnitButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Добавить позицию", None, QtGui.QApplication.UnicodeUTF8))
        self.addUnitButton.setText(QtGui.QApplication.translate("MainWindow", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.editUnitButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Изменить позицию", None, QtGui.QApplication.UnicodeUTF8))
        self.editUnitButton.setText(QtGui.QApplication.translate("MainWindow", "Изменить", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteUnitButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Удалить позицию", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteUnitButton.setText(QtGui.QApplication.translate("MainWindow", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Группы", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Все группы", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Водонагреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Проточные водонагреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Накопительные водонагреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "Теплотехника", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(2).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Электрические конвекторы", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(2).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Маслонаполненные обогреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(3).setText(0, QtGui.QApplication.translate("MainWindow", "Водоснабжение", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(3).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Погружные насосы", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(3).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Центробежные погружные насосы", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(3).child(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Вибрационные погружные насосы", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.filter_label.setText(QtGui.QApplication.translate("MainWindow", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearFilterButton.setText(QtGui.QApplication.translate("MainWindow", "Очистить", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Строка1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Артикул", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Название", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Цена", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Бренд", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Страна производства", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 1)
        item.setText(QtGui.QApplication.translate("MainWindow", "test1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(0, 2)
        item.setText(QtGui.QApplication.translate("MainWindow", "test2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(0, 3)
        item.setText(QtGui.QApplication.translate("MainWindow", "test3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(0, 4)
        item.setText(QtGui.QApplication.translate("MainWindow", "test4", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.goods_tab), QtGui.QApplication.translate("MainWindow", "Справочник товаров", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))

