# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window7.ui'
#
# Created: Thu Jul 26 20:28:18 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1048, 688)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_7 = QtGui.QMenu(self.menu_3)
        self.menu_7.setObjectName(_fromUtf8("menu_7"))
        self.menu_4 = QtGui.QMenu(self.menubar)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.menu_exit = QtGui.QMenu(self.menubar)
        self.menu_exit.setObjectName(_fromUtf8("menu_exit"))
        self.menu_5 = QtGui.QMenu(self.menubar)
        self.menu_5.setObjectName(_fromUtf8("menu_5"))
        self.menu_8 = QtGui.QMenu(self.menubar)
        self.menu_8.setObjectName(_fromUtf8("menu_8"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.action_7 = QtGui.QAction(MainWindow)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.action_9 = QtGui.QAction(MainWindow)
        self.action_9.setObjectName(_fromUtf8("action_9"))
        self.action_open_whsstate = QtGui.QAction(MainWindow)
        self.action_open_whsstate.setObjectName(_fromUtf8("action_open_whsstate"))
        self.action_12 = QtGui.QAction(MainWindow)
        self.action_12.setObjectName(_fromUtf8("action_12"))
        self.action_13 = QtGui.QAction(MainWindow)
        self.action_13.setObjectName(_fromUtf8("action_13"))
        self.action_15 = QtGui.QAction(MainWindow)
        self.action_15.setObjectName(_fromUtf8("action_15"))
        self.action_open_goods = QtGui.QAction(MainWindow)
        self.action_open_goods.setObjectName(_fromUtf8("action_open_goods"))
        self.action_18 = QtGui.QAction(MainWindow)
        self.action_18.setObjectName(_fromUtf8("action_18"))
        self.action_19 = QtGui.QAction(MainWindow)
        self.action_19.setObjectName(_fromUtf8("action_19"))
        self.action_21 = QtGui.QAction(MainWindow)
        self.action_21.setObjectName(_fromUtf8("action_21"))
        self.action_22 = QtGui.QAction(MainWindow)
        self.action_22.setObjectName(_fromUtf8("action_22"))
        self.action_23 = QtGui.QAction(MainWindow)
        self.action_23.setObjectName(_fromUtf8("action_23"))
        self.action_25 = QtGui.QAction(MainWindow)
        self.action_25.setObjectName(_fromUtf8("action_25"))
        self.action_26 = QtGui.QAction(MainWindow)
        self.action_26.setObjectName(_fromUtf8("action_26"))
        self.action_28 = QtGui.QAction(MainWindow)
        self.action_28.setObjectName(_fromUtf8("action_28"))
        self.action_29 = QtGui.QAction(MainWindow)
        self.action_29.setObjectName(_fromUtf8("action_29"))
        self.action_30 = QtGui.QAction(MainWindow)
        self.action_30.setObjectName(_fromUtf8("action_30"))
        self.action_32 = QtGui.QAction(MainWindow)
        self.action_32.setObjectName(_fromUtf8("action_32"))
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_create_db = QtGui.QAction(MainWindow)
        self.action_create_db.setObjectName(_fromUtf8("action_create_db"))
        self.action_change_db = QtGui.QAction(MainWindow)
        self.action_change_db.setObjectName(_fromUtf8("action_change_db"))
        self.action_14 = QtGui.QAction(MainWindow)
        self.action_14.setObjectName(_fromUtf8("action_14"))
        self.action_16 = QtGui.QAction(MainWindow)
        self.action_16.setObjectName(_fromUtf8("action_16"))
        self.action_20 = QtGui.QAction(MainWindow)
        self.action_20.setObjectName(_fromUtf8("action_20"))
        self.action_31 = QtGui.QAction(MainWindow)
        self.action_31.setObjectName(_fromUtf8("action_31"))
        self.action_33 = QtGui.QAction(MainWindow)
        self.action_33.setObjectName(_fromUtf8("action_33"))
        self.action_34 = QtGui.QAction(MainWindow)
        self.action_34.setObjectName(_fromUtf8("action_34"))
        self.action_35 = QtGui.QAction(MainWindow)
        self.action_35.setObjectName(_fromUtf8("action_35"))
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_6 = QtGui.QAction(MainWindow)
        self.action_6.setObjectName(_fromUtf8("action_6"))
        self.action_11 = QtGui.QAction(MainWindow)
        self.action_11.setObjectName(_fromUtf8("action_11"))
        self.action_24 = QtGui.QAction(MainWindow)
        self.action_24.setObjectName(_fromUtf8("action_24"))
        self.action_27 = QtGui.QAction(MainWindow)
        self.action_27.setObjectName(_fromUtf8("action_27"))
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_5)
        self.menu.addAction(self.action_7)
        self.menu.addSeparator()
        self.menu.addAction(self.action_9)
        self.menu_2.addAction(self.action_open_whsstate)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_12)
        self.menu_2.addAction(self.action_13)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_15)
        self.menu_7.addAction(self.action_31)
        self.menu_7.addAction(self.action_33)
        self.menu_7.addAction(self.action_34)
        self.menu_7.addAction(self.action_35)
        self.menu_3.addAction(self.action_open_goods)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_18)
        self.menu_3.addAction(self.action_19)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_21)
        self.menu_3.addAction(self.action_22)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_20)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.menu_7.menuAction())
        self.menu_4.addAction(self.action_23)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_25)
        self.menu_4.addAction(self.action_26)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_28)
        self.menu_4.addAction(self.action_29)
        self.menu_4.addAction(self.action_30)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_32)
        self.menu_exit.addAction(self.action_create_db)
        self.menu_exit.addAction(self.action_change_db)
        self.menu_exit.addSeparator()
        self.menu_exit.addAction(self.action_exit)
        self.menu_5.addAction(self.action_14)
        self.menu_8.addAction(self.action_2)
        self.menu_8.addAction(self.action_6)
        self.menu_8.addSeparator()
        self.menu_8.addAction(self.action_11)
        self.menu_8.addSeparator()
        self.menu_8.addAction(self.action_24)
        self.menu_8.addAction(self.action_27)
        self.menubar.addAction(self.menu_exit.menuAction())
        self.menubar.addAction(self.menu_8.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QObject.connect(self.action_exit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Свободный Учёт", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "Торговля", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "Склад", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_3.setTitle(QtGui.QApplication.translate("MainWindow", "Справочники", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_7.setTitle(QtGui.QApplication.translate("MainWindow", "Группы", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_4.setTitle(QtGui.QApplication.translate("MainWindow", "Деньги", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_exit.setTitle(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_5.setTitle(QtGui.QApplication.translate("MainWindow", "Справка", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_8.setTitle(QtGui.QApplication.translate("MainWindow", "Правка", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "Счета", None, QtGui.QApplication.UnicodeUTF8))
        self.action_3.setText(QtGui.QApplication.translate("MainWindow", "Оплаты по счетам", None, QtGui.QApplication.UnicodeUTF8))
        self.action_4.setText(QtGui.QApplication.translate("MainWindow", "Выдачи по счетам", None, QtGui.QApplication.UnicodeUTF8))
        self.action_5.setText(QtGui.QApplication.translate("MainWindow", "Возвраты по счетам", None, QtGui.QApplication.UnicodeUTF8))
        self.action_7.setText(QtGui.QApplication.translate("MainWindow", "Счета-фактуры", None, QtGui.QApplication.UnicodeUTF8))
        self.action_9.setText(QtGui.QApplication.translate("MainWindow", "Отчёты", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open_whsstate.setText(QtGui.QApplication.translate("MainWindow", "Состояние склада", None, QtGui.QApplication.UnicodeUTF8))
        self.action_12.setText(QtGui.QApplication.translate("MainWindow", "Приходы", None, QtGui.QApplication.UnicodeUTF8))
        self.action_13.setText(QtGui.QApplication.translate("MainWindow", "Уходы", None, QtGui.QApplication.UnicodeUTF8))
        self.action_15.setText(QtGui.QApplication.translate("MainWindow", "Отчёты", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open_goods.setText(QtGui.QApplication.translate("MainWindow", "Товары", None, QtGui.QApplication.UnicodeUTF8))
        self.action_18.setText(QtGui.QApplication.translate("MainWindow", "Фирмы", None, QtGui.QApplication.UnicodeUTF8))
        self.action_19.setText(QtGui.QApplication.translate("MainWindow", "Контрагенты", None, QtGui.QApplication.UnicodeUTF8))
        self.action_21.setText(QtGui.QApplication.translate("MainWindow", "Кошельки", None, QtGui.QApplication.UnicodeUTF8))
        self.action_22.setText(QtGui.QApplication.translate("MainWindow", "Статьи доходов и расходов", None, QtGui.QApplication.UnicodeUTF8))
        self.action_23.setText(QtGui.QApplication.translate("MainWindow", "Календарь платежей", None, QtGui.QApplication.UnicodeUTF8))
        self.action_25.setText(QtGui.QApplication.translate("MainWindow", "Поступления", None, QtGui.QApplication.UnicodeUTF8))
        self.action_26.setText(QtGui.QApplication.translate("MainWindow", "Расходы", None, QtGui.QApplication.UnicodeUTF8))
        self.action_28.setText(QtGui.QApplication.translate("MainWindow", "Оплаты контрагентов", None, QtGui.QApplication.UnicodeUTF8))
        self.action_29.setText(QtGui.QApplication.translate("MainWindow", "Выплаты контрагентам", None, QtGui.QApplication.UnicodeUTF8))
        self.action_30.setText(QtGui.QApplication.translate("MainWindow", "Долги контрагентов", None, QtGui.QApplication.UnicodeUTF8))
        self.action_32.setText(QtGui.QApplication.translate("MainWindow", "Отчёты", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MainWindow", "Выход", None, QtGui.QApplication.UnicodeUTF8))
        self.action_create_db.setText(QtGui.QApplication.translate("MainWindow", "Создать новую базу данных", None, QtGui.QApplication.UnicodeUTF8))
        self.action_change_db.setText(QtGui.QApplication.translate("MainWindow", "Смена базы данных", None, QtGui.QApplication.UnicodeUTF8))
        self.action_14.setText(QtGui.QApplication.translate("MainWindow", "Справка по программе", None, QtGui.QApplication.UnicodeUTF8))
        self.action_16.setText(QtGui.QApplication.translate("MainWindow", "Настройки", None, QtGui.QApplication.UnicodeUTF8))
        self.action_20.setText(QtGui.QApplication.translate("MainWindow", "Задачи", None, QtGui.QApplication.UnicodeUTF8))
        self.action_31.setText(QtGui.QApplication.translate("MainWindow", "Товаров", None, QtGui.QApplication.UnicodeUTF8))
        self.action_33.setText(QtGui.QApplication.translate("MainWindow", "Контрагентов", None, QtGui.QApplication.UnicodeUTF8))
        self.action_34.setText(QtGui.QApplication.translate("MainWindow", "Статей  доходов/расходов ", None, QtGui.QApplication.UnicodeUTF8))
        self.action_35.setText(QtGui.QApplication.translate("MainWindow", "Задач", None, QtGui.QApplication.UnicodeUTF8))
        self.action_2.setText(QtGui.QApplication.translate("MainWindow", "Отменить", None, QtGui.QApplication.UnicodeUTF8))
        self.action_6.setText(QtGui.QApplication.translate("MainWindow", "Вернуть", None, QtGui.QApplication.UnicodeUTF8))
        self.action_11.setText(QtGui.QApplication.translate("MainWindow", "Настройка печатных форм", None, QtGui.QApplication.UnicodeUTF8))
        self.action_24.setText(QtGui.QApplication.translate("MainWindow", "Настройка программы", None, QtGui.QApplication.UnicodeUTF8))
        self.action_27.setText(QtGui.QApplication.translate("MainWindow", "Администрирование", None, QtGui.QApplication.UnicodeUTF8))

