# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'whsstate11-new.ui'
#
# Created: Mon Aug 13 23:31:47 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WhsStateForm(object):
    def setupUi(self, WhsStateForm):
        WhsStateForm.setObjectName(_fromUtf8("WhsStateForm"))
        WhsStateForm.resize(1004, 653)
        font = QtGui.QFont()
        font.setPointSize(11)
        WhsStateForm.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(WhsStateForm)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(WhsStateForm)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(6)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupstreeWidget = QtGui.QTreeWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupstreeWidget.sizePolicy().hasHeightForWidth())
        self.groupstreeWidget.setSizePolicy(sizePolicy)
        self.groupstreeWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.groupstreeWidget.setMaximumSize(QtCore.QSize(450, 16777215))
        self.groupstreeWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupstreeWidget.setFont(font)
        self.groupstreeWidget.setObjectName(_fromUtf8("groupstreeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.groupstreeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.groupstreeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.groupstreeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.groupstreeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.whsstateTable = QtGui.QTableWidget(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.whsstateTable.setFont(font)
        self.whsstateTable.setFrameShape(QtGui.QFrame.StyledPanel)
        self.whsstateTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.whsstateTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.whsstateTable.setGridStyle(QtCore.Qt.SolidLine)
        self.whsstateTable.setObjectName(_fromUtf8("whsstateTable"))
        self.whsstateTable.setColumnCount(8)
        self.whsstateTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.whsstateTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.whsstateTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.whsstateTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.whsstateTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.whsstateTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.whsstateTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.whsstateTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.whsstateTable.setHorizontalHeaderItem(7, item)
        self.whsstateTable.horizontalHeader().setCascadingSectionResizes(False)
        self.whsstateTable.horizontalHeader().setSortIndicatorShown(True)
        self.whsstateTable.horizontalHeader().setStretchLastSection(True)
        self.whsstateTable.verticalHeader().setSortIndicatorShown(False)
        self.whsstateTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBox = QtGui.QComboBox(WhsStateForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox)
        self.filter_label = QtGui.QLabel(WhsStateForm)
        self.filter_label.setObjectName(_fromUtf8("filter_label"))
        self.horizontalLayout.addWidget(self.filter_label)
        self.filter_lineEdit = QtGui.QLineEdit(WhsStateForm)
        self.filter_lineEdit.setObjectName(_fromUtf8("filter_lineEdit"))
        self.horizontalLayout.addWidget(self.filter_lineEdit)
        self.ClearFilterButton = QtGui.QPushButton(WhsStateForm)
        self.ClearFilterButton.setObjectName(_fromUtf8("ClearFilterButton"))
        self.horizontalLayout.addWidget(self.ClearFilterButton)
        self.CloseWhsStateButton = QtGui.QPushButton(WhsStateForm)
        self.CloseWhsStateButton.setObjectName(_fromUtf8("CloseWhsStateButton"))
        self.horizontalLayout.addWidget(self.CloseWhsStateButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(WhsStateForm)
        QtCore.QObject.connect(self.ClearFilterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.filter_lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(WhsStateForm)
        WhsStateForm.setTabOrder(self.comboBox, self.filter_lineEdit)
        WhsStateForm.setTabOrder(self.filter_lineEdit, self.ClearFilterButton)
        WhsStateForm.setTabOrder(self.ClearFilterButton, self.CloseWhsStateButton)

    def retranslateUi(self, WhsStateForm):
        WhsStateForm.setWindowTitle(QtGui.QApplication.translate("WhsStateForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.headerItem().setText(0, QtGui.QApplication.translate("WhsStateForm", "Группы", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.groupstreeWidget.isSortingEnabled()
        self.groupstreeWidget.setSortingEnabled(False)
        self.groupstreeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("WhsStateForm", "Все группы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("WhsStateForm", "Водонагреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("WhsStateForm", "Проточные водонагреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("WhsStateForm", "Накопительные водонагреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("WhsStateForm", "Теплотехника", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.topLevelItem(2).child(0).setText(0, QtGui.QApplication.translate("WhsStateForm", "Электрические конвекторы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.topLevelItem(2).child(1).setText(0, QtGui.QApplication.translate("WhsStateForm", "Маслонаполненные обогреватели", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.topLevelItem(3).setText(0, QtGui.QApplication.translate("WhsStateForm", "Водоснабжение", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.topLevelItem(3).child(0).setText(0, QtGui.QApplication.translate("WhsStateForm", "Погружные насосы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.topLevelItem(3).child(0).child(0).setText(0, QtGui.QApplication.translate("WhsStateForm", "Центробежные погружные насосы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.topLevelItem(3).child(0).child(1).setText(0, QtGui.QApplication.translate("WhsStateForm", "Вибрационные погружные насосы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupstreeWidget.setSortingEnabled(__sortingEnabled)
        self.whsstateTable.setSortingEnabled(True)
        item = self.whsstateTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("WhsStateForm", "Артикул", None, QtGui.QApplication.UnicodeUTF8))
        item = self.whsstateTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("WhsStateForm", "Название", None, QtGui.QApplication.UnicodeUTF8))
        item = self.whsstateTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("WhsStateForm", "Цена", None, QtGui.QApplication.UnicodeUTF8))
        item = self.whsstateTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("WhsStateForm", "В наличии", None, QtGui.QApplication.UnicodeUTF8))
        item = self.whsstateTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("WhsStateForm", "Резерв", None, QtGui.QApplication.UnicodeUTF8))
        item = self.whsstateTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("WhsStateForm", "Ед. изм.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.whsstateTable.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("WhsStateForm", "В упаковке", None, QtGui.QApplication.UnicodeUTF8))
        item = self.whsstateTable.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("WhsStateForm", "Упак. в наличии", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("WhsStateForm", "Товары в наличии", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("WhsStateForm", "Все товары", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_label.setText(QtGui.QApplication.translate("WhsStateForm", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearFilterButton.setText(QtGui.QApplication.translate("WhsStateForm", "Очистить", None, QtGui.QApplication.UnicodeUTF8))
        self.CloseWhsStateButton.setToolTip(QtGui.QApplication.translate("WhsStateForm", "Закрыть окно", None, QtGui.QApplication.UnicodeUTF8))
        self.CloseWhsStateButton.setText(QtGui.QApplication.translate("WhsStateForm", "Закрыть", None, QtGui.QApplication.UnicodeUTF8))

